### ISSUE TITLE
new power module

### ISSUE THREAD

**Issue by gkasprow** [sinara-hw/EEM_PWR_MOD_AC#1]
The time has come! The power module is simple, low cost and robust. It's based on RPS400-12 power module.
I added load indicator (4 LEDs), EMC filter and metal cover. 

![obraz](https://user-images.githubusercontent.com/4325054/102700576-f332b100-424e-11eb-985f-9adb7eb3aa75.png)
![obraz](https://user-images.githubusercontent.com/4325054/102700586-1198ac80-424f-11eb-9955-7bc55544c86b.png)
![obraz](https://user-images.githubusercontent.com/4325054/102700601-355bf280-424f-11eb-9a91-b1a6c1e1e682.png)

**Comment by gkasprow** [comment]
It's modification of the CPCIS version, with other connector, front panel IEC socket and without all management. The mechanics, PCB shape was already verified.

**Comment by dtcallcock** [comment]
Can you add pdfs to v1.0rc1 release @gkasprow if you have time?

**Comment by gkasprow** [comment]
done
