### ISSUE TITLE
Change J3 part

### ISSUE THREAD

**Issue by kaolpr** [sinara-hw/EEM_PWR_MOD_AC#10]
Currently J3 (AC connector for EPP-400) is of type MOLEX_26-62-4030 which is different from the one on the EPP-400. Maybe we could change it to AMP-TE  1-1123723-3 (JST suggested in EPP datasheet is hardly available)  that cable can have the same plugs on both ends?

**Comment by gkasprow** [comment]
OK, replaced with JST one which is available from Farnell

**Comment by gkasprow** [comment]
I added also comment that can AMP-TE 1-1123723-3 can be used instead
