### ISSUE TITLE
Screws outside clearance

### ISSUE THREAD

**Issue by jordens** [sinara-hw/EEM_PWR_MOD_AC#11]
The four screws that attach the PCB underside cover to the upper cover (two are visible at https://user-images.githubusercontent.com/4325054/108885730-6f0ef800-7608-11eb-81cf-571b436ed6ca.jpg) interfere with guide rails of module storage systems.
If possible the covers should be changed to be narrower, or the screws should be moved (attach front and back instead of on the sides), or the screws should be made flatter.

**Comment by gkasprow** [comment]
The scews should be countersunk type (I think they are) and the shield should have chamfered holes.

**Comment by jordens** [comment]
I got black round top screws, not countersunk. And the sheet metal didn't have any visible chamfering. If the BOM and mechanical designs are already clear, complete, and correct here we can close this as manufacturing deviation.

**Comment by gkasprow** [comment]
@pkozakiewicz ?

**Comment by pkozakiewicz** [comment]
I do not recognize the device in Robert's picture as ours have black powder painted cover. This one has also FDM printed front panel (?). I am pretty sure that we overcame this in the newest revision.

I see no collision with guide rail in our case and we do not use countersunk holes. Please see a picture. We used our v1.2 PSUs in multiple setups and it was never an issue.
![signal-2023-07-20-121957_002](https://github.com/sinara-hw/EEM_PWR_MOD_AC/assets/59871387/6cfa0ad8-2f8f-41e6-b4dd-b35faf9def65)

**Comment by jordens** [comment]
Those are not countersunk screws and the covers are not chamfered.
The screws touch the rail even in a normal crate. In board storage systems there is always the next board guide adjacent and the screws interfere with them.

![image](https://github.com/sinara-hw/EEM_PWR_MOD_AC/assets/1338946/d3625763-af21-4011-8157-0ef562b28f2f)
![image](https://github.com/sinara-hw/EEM_PWR_MOD_AC/assets/1338946/a9ead58e-9af3-4273-bdab-1c50fa9d7520)

**Comment by pkozakiewicz** [comment]
I see. The metal sheet may be be too thin to apply countersunk holes (0.85 mm incl. powder coating). As a temporary solution we will look for screws with lower head as the one used is >2 mm.

In the next revision cutouts in the PCB outline should be enlarged to make room for embossing in the cover in order to hide the screws.

**Comment by jordens** [comment]
Oh yes. Embossing is a nice solution here assuming there is space behind!

**Comment by pkozakiewicz** [comment]
There are no obstacles behind current screw positions that would prevent us from doing this, but the size of PSU module itself makes the design difficult to assemble. It would be good to save some space by replacing it with some alternative with a more compact design.
