### ISSUE TITLE
Front panel offset

### ISSUE THREAD

**Issue by jakgajewski** [sinara-hw/EEM_PWR_MOD_AC#4]
Front panel part number should be 30848-430 (0,1" offset) with handle 20817-682 (0,1" offset).
For rails 24560-359 (0,1" offset).

https://schroff.nvent.com/en-gb/products/plug-unit-u-profile-front-panel-iel-iet-type-2-01-offset/enc30848-430#product-details-section
https://schroff.nvent.com/en-gb/products/inserterextractor-handle-type-iel-black-01-offset/enc20817-682
https://schroff.nvent.com/en-gb/products/guide-rail-coding-compactpci-vme64x-offset-01/enc24560-359

**Comment by jakgajewski** [comment]
Additionally, only two M3 nuts are required for mechanics assembly

**Comment by gkasprow** [comment]
fixed
