### ISSUE TITLE
Mechanical design

### ISSUE THREAD

**Issue by kaolpr** [sinara-hw/EEM_PWR_MOD_AC#9]
After assembling 2 units I have to say that mechanical design of PCB and housing **needs** to be changed:

1. The cutout for the power module is too small  and PCB sometimes collides with a heatsink. Seems to be dependent on the particular MW module, had to choose one that will fit. Nevertheless, there should be some margin to accommodate for assembly tolerances.

![image](https://user-images.githubusercontent.com/9166701/123394925-f2812b80-d59f-11eb-8568-b69df81f879d.png)

2. There is not enough space for 12V / GND cabling. Though it *can be done*, it's very time consuming and cables must be fitted between power module elements.

Suggest extending PCB by 15 mm and exchanging connectors to straight. This will not take more space then current solution and will give a lot more room for cabling. MOLEX_39-28-1043 (straight one) with plug connected has height of 23.6 mm, whereas available height to the adjacent module plane is ~35 mm, so for bending power cable we would have ~10mm.

![image](https://user-images.githubusercontent.com/9166701/123407614-70e3ca80-d5ac-11eb-96e9-40be9dda4495.png)

We could also extend cutout easily and, after extending case (red line), also power buds would be covered:

![image](https://user-images.githubusercontent.com/9166701/123407980-d33ccb00-d5ac-11eb-83fc-452a92e73d8b.png)

**Comment by gkasprow** [comment]
Make sure that vertical plugs fit within 8HP

**Comment by kaolpr** [comment]
Well, I tried, and it looks OK, though not very elegant. Alternatively we can keep angled connectors accepting the fact that the module will be longer by 15mm.

**Comment by kaolpr** [comment]
Well, it will be a bit cramped... I have some doubts on whether it will be possible to bend those cables when first module after PSU will be replaced (without removing back cover and adjusting them by hand). Thus, I'd opt for keeping angled connectors and extending module length by 15mm.

![image](https://user-images.githubusercontent.com/9166701/124600802-686e7800-de67-11eb-9926-688daca81291.png)

**Comment by gkasprow** [comment]
let's make it longer.

**Comment by gkasprow** [comment]
fixed 
![obraz](https://user-images.githubusercontent.com/4325054/129877623-20064052-2548-4e14-95ed-e59ee2518748.png)
![obraz](https://user-images.githubusercontent.com/4325054/129877670-b70ed5c5-c738-4a75-8836-d4f674eb97ad.png)
